// <auto-generated />
using System;
using BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BE.Models.ApplicationProgram", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgramId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProgramId");

                    b.ToTable("ApplicationPrograms");

                    b.HasData(
                        new
                        {
                            ProgramId = 1,
                            Name = "Chất lượng cao"
                        },
                        new
                        {
                            ProgramId = 2,
                            Name = "Tiên tiến"
                        },
                        new
                        {
                            ProgramId = 3,
                            Name = "Đại trà"
                        });
                });

            modelBuilder.Entity("BE.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FacultyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            FacultyId = 1,
                            Name = "Khoa Luật"
                        },
                        new
                        {
                            FacultyId = 2,
                            Name = "Khoa Tiếng Anh thương mại"
                        },
                        new
                        {
                            FacultyId = 3,
                            Name = "Khoa Tiếng Nhật"
                        },
                        new
                        {
                            FacultyId = 4,
                            Name = "Khoa Tiếng Pháp"
                        });
                });

            modelBuilder.Entity("BE.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("StudentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("StatusId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "22127389",
                            Address = "Bình Chánh",
                            Course = 2022,
                            DateOfBirth = new DateTime(2004, 1, 15, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "thanh1612004@gmail.com",
                            FacultyId = 1,
                            FullName = "Nguyễn Phúc Thành",
                            Gender = 1,
                            PhoneNumber = "0915361073",
                            ProgramId = 1,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("BE.Models.StudentStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("StudentStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "Đang học"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "Đã tốt nghiệp"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "Đã thôi học"
                        },
                        new
                        {
                            StatusId = 4,
                            Name = "Tạm dừng học"
                        });
                });

            modelBuilder.Entity("BE.Models.Student", b =>
                {
                    b.HasOne("BE.Models.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.ApplicationProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.StudentStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Program");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
